### ISSUE TITLE
[META] Use django-haystack for search in mozillians.org

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#116]
Meta issue to track the work needed to refactor search in mozillians.org.

- [x] [Install and configure Haystack](https://github.com/mozilla/parsys/issues/122)
- [x] [Create basic group and profile indexes](https://github.com/mozilla/parsys/issues/123)
- [x] [Re-create indexes on every release](https://github.com/mozilla/parsys/issues/124)
- [x] [Remove old code](https://github.com/mozilla/parsys/issues/125)
- [ ] [META - Aucomplete, Scoring and Faceting](https://github.com/mozilla/parsys/issues/126)
- [x] [Update profile index on profile update](https://github.com/mozilla/parsys/issues/137)
- [x] [Update group index on group update](https://github.com/mozilla/parsys/issues/144)
- [x] [Update UI for search?](https://github.com/mozilla/parsys/issues/138)
- [x] [Update indexes through the admin](https://github.com/mozilla/parsys/issues/143)
- [x] [Exclude non visible groups from search.](https://github.com/mozilla/parsys/issues/142)
- [x] [Search in related fields](https://github.com/mozilla/parsys/issues/141)
- [x] [Enable search in groups.](https://github.com/mozilla/parsys/issues/145)
- [x] [Helper method for ES conf](https://github.com/mozilla/parsys/issues/146)
- [x] [Search suggestions.](https://github.com/mozilla/parsys/issues/147)
- [ ] [Use a queue to update the index..](https://github.com/mozilla/parsys/issues/149)
- [x] [Limit search in models.](https://github.com/mozilla/parsys/issues/152)
- [ ] [Haystack admin search](https://github.com/mozilla/parsys/issues/154)
- [x] [Exclude groups from public search](https://github.com/mozilla/parsys/issues/156)
- [x] [Search doesn't work for anonymous users.](https://github.com/mozilla/parsys/issues/153)
- [ ] [Filter out incomplete profiles from the results](https://github.com/mozilla/parsys/issues/194)
- [ ] [Log anonymized search data.](https://github.com/mozilla/parsys/issues/200)
