### ISSUE TITLE
DRAFT Sprint Goal J

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/parsys#362]
### Events Utility 
- Move to Salesforce Production #299
- Release Mozillians.org group permissions integration #335
- Release 3 localized themes #303
- Get Brand approval on Mozilla Generic and Firefox Generic event landing pages #366
- Get first versions of event 'cards' used in social sharing and discovery pages #370
- Get first versions of email templates (visuals) #371
- Align on triggered emails with LCM #372
- Fix one Observatory issue #313

#### Event Bugs
- [ ] Unsubscribe needs to be limited to just the one event and event host #323
- [ ] State field in RSVP form #373
- [X] Permissions aren't loaded on second login #374
- [ ] Autopopulation on discovery pages of events #375

### Blind Code Reviews
- Draft Experimentation plan #306
- Schedule discussion with Firefox Engineering Team volunteers #376
