### ISSUE TITLE
Events - Sprint Goal Beta - July 10th 2018

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/parsys#397]
* Event Discovery Theme 
- [x] Mozilla.org - Schedule 2 meetings (IA and pocket) from David Tenser email #398
- [x] Events.mozilla.org - Scope Auto-population functionality with Splash #399
- [ ] Events.mozilla.org - Scope using the Design Protocol with Splash #400
- [x] Identify who can help with attribute handling from the Website team #401

* Release 1 iterations
- [x] Language theme naming updated #402
- [x] Jeremie’s French event -> French theme #403
- [x]  Daniel’s English event -> English theme #403
- [ ]  Flag this event form- Update design and name #404
- [ ] Schedule time with Design team - people want to customize their themes, what’s our comfort level with this? #405

* View Source
- [x] Help VS team update urls #406

* Splash Product work - need commitments from Splash
- [ ] Tracking removal - remove unnecessary trackers #407
- [x] Schedule the Observatory score meeting with April #408
- [ ] Fix - Permissions checked on every login #395
- [x] Get Payment processing fees information just as an FYI #409

* GDPR
- [ ] Contact import consent feature #412
- [ ] Intro email for opt in #413

* Splash relationship
- [ ] Give feedback on new Joint project plan #410
- [ ] follow up with Will Evans #411

* Community Rollout
- [x] Follow up with Lucy on her team's community recommendations #414

* Splash Bugs
- [ ] https://github.com/mozilla/events-issues/issues/13

* Event Support
- [x] Comments in Quick Start guide #415
- [x] Add section on how the language themes work #415
- [ ] Schedule training calls #416
