### ISSUE TITLE
Events - Sprint Gamma - July 25th

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/parsys#417]
## Event Discovery Theme
- [x] Met with website team - align on next steps (send recap) #400
- [ ] Get a few links to start theming page - for styling and functional elements like nav and footer #400
     - [x] Password protect the events discovery page #400
     - [ ] Screencast of how the hub works #400
     - [ ] Get list of tags from the editorial team for seeding the attribute list #401
- [x] Meet with Raphael about SEO #418
- [ ] Events.mozilla.org - Scope Auto-population functionality with Splash - test iframe short term option with splash #399

---

## Splash Product work 
- [ ] Tracking removal - remove unnecessary trackers - follow up with Splash for an update #407
- [x] Get video from the Observatory score meeting with April 
- [ ] Fix - Permissions checked on every login - get time for QA on calendar #395
- [x] Payment processing fees information - send to finance 
- [ ] GDPR - follow up with splash on release timing
- [ ] Contact import consent #412
- [ ] Intro email for opt in #413

---

## Community Rollout
- [ ] CPG link in the footer - goal: some for the attendees #419
- [ ] CPG acceptance for event hosts #419
- [ ] Scope key word triggers with vendor #420
     - [ ] Get list from vendor of their current words #420
     - [ ] Get list of desired words from lucy #420
     - [ ] Understand what happens if you use a triggered word #420
- [ ] Edit the “flag form” categories to simplify internal triage. #404
- [ ] Set-up a triage strategy/plan with Kate M #421
- [x] General walk-thorough with Kate and Emma  #422

---

## Other
- [x] Schedule work week #423
- [ ] Reply/close/assess user filed issues 
- [x] Start scoping ‘universal blocking’ with the IAM team #424
