### ISSUE TITLE
Events - Sprint Delta - 08 Aug - 17 Aug

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/parsys#425]
## Event Discovery Theme
- [x] Arielle intro Viorela to website team
- [ ] Get a few links to start theming page - for styling and functional elements like nav and footer #400
     - [x] Un-password protect the events discovery page and turn back to ‘Coming Soon’
     - [ ] Get list of tags from the editorial team for seeding the attribute list #401
- [ ] Events.mozilla.org - Scope Auto-population functionality with Splash - test iframe short term option with splash #399

---

## Splash Product work 
- [ ] Tracking removal - remove unnecessary trackers - follow up with Splash for an update #407
- [x] Fix - Permissions checked on every login - QA #395
- [x] Payment processing fees information - send to finance 
- [ ] GDPR - follow up with splash on release timing
- [ ] Contact import consent #412
- [ ] Intro email for opt in #413
- [x] Only admins and analysts should be able to access /reporting page #426 
- [x] All roles except Mozilla admins should have access only to Profile and Settings tabs #427
- [ ] Event collaborators who created an account in splash outside of Mozilla org can see all guests email addresses #428
- [x] Integration with slack public channel - don’t allow community members to integrate their event with slack #429
---

## Community Rollout
- [ ] CPG link in the footer - goal: some for the attendees #419
- [ ] CPG acceptance for event hosts #419
- [ ] Edit the “flag form” categories to simplify internal triage. #404
- [ ] Set-up a triage strategy/plan with Kate M #421

---

## Other
- [x] Schedule work week #423
- [ ] Reply/close/assess user filed issues 
- [ ] Delete test events from Salesforce and Splash #430
