### ISSUE TITLE
Events - Sprint Epsilon - 21 Aug - 30 Aug

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/parsys#431]
- [ ] Create a transition plan for day to day work from Arielle to Viorela #432

## Event Discovery Theme
- [ ] Deliver a draft theme for discovery page 
- [ ] Feedback from website team (Yuliya) 
- [x] Get list of tags from the editorial team for seeding the attribute list #401
- [ ] Events.mozilla.org - Scope Auto-population functionality with Splash - test iframe short term option with splash #399

---

## Splash Product work 
- [ ] Tracking removal - remove unnecessary trackers - follow up with Splash for an update #407
- [ ] Intro email for opt in #413
- [ ] Only admins and analysts should be able to access /reporting page #426 
- [ ] Event collaborators who created an account in splash outside of Mozilla org can see all guests email addresses #428
---

## Community Rollout
- [x] CPG link in the footer - get approval from Community Development team #419
- [ ] CPG acceptance for event hosts -  request to splash to add language to the create event page #419
- [x] Edit the “flag form” categories to simplify internal triage - get approval from Community Development team #404
- [ ] Set-up a triage strategy/plan with Kate M #421

---

## Other
- [ ] Define next Splash Releases #433
- [ ] Reply/close/assess user filed issues 
- [ ] Delete test events from Salesforce #430
