### ISSUE TITLE
Events - Sprint Eta - 18 Sep - 27 Sep

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/parsys#436]
## Product + Bugs:
- [x] Verify the Sessions feature #437
- [ ] Update Events Utility document with information on new features and releases #438
- [x] Review Release Business Requirement document created by Splash #439
- [ ] External Collaborator Options - updated email
- [x] iOS App login doesn’t work #440
- [x] Gather requirements from Tech Speakers group on specific program configuration #441
- [ ] Triage / request update on logged bugs

## Community Rollout
- [x] CPG acceptance for event hosts on Create event page #419
- [x] GDPR compliant Intro email for opt in #413
- [ ] Add new event types for community like Rust, reps, Marketing #442
- [ ] Create a Meetup theme #443
- [ ] Update support materials for community events #444
- [ ] Get dedicated feedback from a team of contributors chosen by the CD team #445

## Event discovery
- [x] Get Feedback from website team on all events page (Yuliya) #446
