### ISSUE TITLE
Events - Sprint Theta - 2 Oct - 11 Oct

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/parsys#448]
## Product + Bugs:
- [x] Update RSVP form for all themes (remove neon colors, use black / white instead) #449
- [ ] Update Events Utility document with information on new features and releases #438
- [x] External Collaborator Options #457
- [ ] Triage bugs / close fixed github issues 
- [x] Checklist for event hosts - explore sending an email to new logins #458

## Programmatic 
- [x] Tech Speakers - deliver hub page #450
- [x] Potentially Identify a point of contact for scoping replacing Reps Events #452
- [ ] Get sessions proposal ready for Brianna to review #451

## Metrics
- [ ] Alignment meeting with Susy #453

## Community rollout
- [x] Follow up on GDPR contact import acceptance #412
- [x] Create a Meetup theme, with less sections  #443
- [ ] Update support materials for community events #444
- [x] Get dedicated feedback from a team of contributors chosen by the CD team - on themes (most likely Reps Council, will confirm with Konstantina) #445
- [x] Review Publishing process for event discovery with Lucy #454

## Event discovery
- [ ] Event types filter bug #455
- [ ] All MoCo-MoFo email with website team #456
