### ISSUE TITLE
Events - Sprint Iota - 16th Oct - 25th Oct

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/parsys#459]
## Product + Bugs:
- [x] Update Events Utility document with information on new features and releases #438
- [x] Highlight done and in progress items in our release spreadsheet #467
- [x] External Collaborator - footer approval #457
- [x] Triage bugs / close fixed github issues #468  
- [ ] Splash 4 Testing #460
- [x] Salesforce clean up #461
- [ ] Add new recommended theme blocks #462
- [ ] Release 2.2  #463

## Programmatic 
- [x] Tech Speakers - deliver demo page #464
- [ ] Reps #465
- [x] Get sessions proposal ready for Brianna to review #451
- [x] Follow up with Add-ons #466
