### ISSUE TITLE
Events - Sprint Kappa - 30th Oct - 8th Nov

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/parsys#469]
## Product + Bugs:
- [ ] Investigate Salesforce email sign up issue
- [ ] Splash 4 Testing #460
- [ ] Add new recommended theme blocks #462
- [ ] Release 2.2  #463
- [ ] Updates to the main hub page (featured events)
- [ ] English/French theme updates
- [ ] IT transition plan

## Programmatic 
- [ ] Tech Speakers - investigate performance bug
- [ ] Reps #465
- [x] Get sessions proposal ready for Brianna to review #451
- [x] Follow up with Add-ons #466

## Support planning
- [ ] Slack channel
- [ ] Wiki help
